import { mkdirSync } from "node:fs";
import { dirname } from "node:path";

export async function writeJobsReport(store, outputPath = "Jobs.md") {
  const candidates = store.listCandidates();
  const markdown = renderJobsMarkdown(candidates);
  mkdirSync(dirname(outputPath), { recursive: true });
  await Bun.write(outputPath, markdown);
  return { outputPath, count: candidates.length };
}

export function renderJobsMarkdown(candidates) {
  const lines = [
    "# Jobs",
    "",
    "Generated from persisted job candidates. Do not edit this file as the source of truth; rerun the jobs pipeline instead.",
    ""
  ];

  if (candidates.length === 0) {
    lines.push("No candidates stored yet.", "");
    return lines.join("\n");
  }

  candidates.forEach((candidate, index) => {
    lines.push(`## ${index + 1}. ${candidate.title}`);
    lines.push("");
    lines.push(`**Hiring company:** ${candidate.company}  `);
    addOptional(lines, "Company website", candidate.companyWebsite);
    addOptional(lines, "LinkedIn publisher", candidate.publisherCompany);
    lines.push(`**Source:** ${candidate.source}  `);
    lines.push(`**Job ID:** ${candidate.id}  `);
    lines.push(`**URL:** ${candidate.url}  `);
    addOptional(lines, "Posted", candidate.postedAt);
    addOptional(lines, "Geography / remote scope", candidate.remoteScope || candidate.location);
    addOptional(lines, "Employment type", candidate.employmentType);
    addOptional(lines, "Salary range", candidate.salaryRange);
    addOptional(lines, "Verification note", candidate.verificationNote);
    lines.push("");
    lines.push("**JD:**");
    lines.push("");
    lines.push(candidate.description || "No description captured yet.");
    lines.push("");
  });

  return lines.join("\n");
}

function addOptional(lines, label, value) {
  if (value) lines.push(`**${label}:** ${value}  `);
}
